#!/bin/sh
#  File: sbsrc/templates/.default_vnc_xstartup_template
#
#  Abstract:
#     SBTools xstartup file to use with VNC servers.
#
#     It sources a common VNC config that should not be modified locally.
#     It also includes a Customizable section.
#
#     To install this configuration (e.g. ~/.vnc/xstartup),
#     run sbsetupunix and follow the instructions.
#
#     xstartup will search for a working window manager.
#     If you'd like to use a specific window manager such as xfce4, define it via:
#       (tcsh) setenv SBTOOLS_VNC_WINDOW_MGR startxfce4
#       (bash) export SBTOOLS_VNC_WINDOW_MGR=startxfce4
#       vncserver
#
#  Generation:
#      This is generated via SBTOOLS/sbsrc/templates/Makefile
#

# SBTools Master VNC Configuration
. /mathworks/hub/share/sbtools/xstartup_master

xtermCmd=xterm
arch=`/mathworks/hub/share/sbtools/sbarch.sh`
if [ $arch = "glnx86" -o $arch = "glnxa64" ]
then
    which startxfce4 > /dev/null
    if [ $? -eq 0 ]
    then
        xtermCmd=gnome-terminal
    else
        xtermCmd=konsole
    fi
fi

##### --- Custom VNC Configuration Starts Below This Line --- #####

. ~/.xinitrc
